# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Daud Tasleem
"""
Mesh export utilities: OBJ, PLY, and raw numpy arrays.

All exporters take 3-D vertex arrays (N, 3) and face index arrays (F, 3).
"""

from __future__ import annotations

from pathlib import Path
import struct

import numpy as np


# ─── OBJ ─────────────────────────────────────────────────────────────────────

def to_obj(
    vertices: np.ndarray,
    faces: np.ndarray,
    path: str | Path,
    name: str = "slab",
) -> None:
    """Write a Wavefront OBJ file.

    Parameters
    ----------
    vertices : shape (N, 3), world-frame coordinates in metres.
    faces    : shape (F, 3), zero-based triangle vertex indices.
    path     : output ``.obj`` file path.
    name     : object name embedded in the file header.
    """
    path = Path(path)
    with path.open("w") as f:
        f.write("# Generated by ifc-slab-mesh v0.1.0\n")
        f.write(f"o {name}\n")
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        for tri in faces:
            # OBJ uses 1-based indices
            f.write(f"f {tri[0]+1} {tri[1]+1} {tri[2]+1}\n")


# ─── PLY (binary little-endian) ───────────────────────────────────────────────

def to_ply(
    vertices: np.ndarray,
    faces: np.ndarray,
    path: str | Path,
) -> None:
    """Write a binary PLY file (little-endian float32 vertices).

    Parameters
    ----------
    vertices : shape (N, 3)
    faces    : shape (F, 3), zero-based triangle vertex indices.
    path     : output ``.ply`` file path.
    """
    path = Path(path)
    nv = len(vertices)
    nf = len(faces)

    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        "comment Generated by ifc-slab-mesh v0.1.0\n"
        f"element vertex {nv}\n"
        "property float x\n"
        "property float y\n"
        "property float z\n"
        f"element face {nf}\n"
        "property list uchar int vertex_indices\n"
        "end_header\n"
    )

    with path.open("wb") as f:
        f.write(header.encode("ascii"))
        # Vertices: 3 × float32
        verts_f32 = vertices.astype(np.float32)
        f.write(verts_f32.tobytes())
        # Faces: uchar(3) + 3 × int32
        for tri in faces:
            f.write(struct.pack("<Biii", 3, int(tri[0]), int(tri[1]), int(tri[2])))


# ─── numpy ───────────────────────────────────────────────────────────────────

def to_npz(
    vertices: np.ndarray,
    faces: np.ndarray,
    path: str | Path,
) -> None:
    """Save vertices and faces as a compressed numpy archive."""
    np.savez_compressed(str(path), vertices=vertices, faces=faces)


def load_npz(path: str | Path) -> tuple[np.ndarray, np.ndarray]:
    """Load a numpy archive saved by ``to_npz``."""
    data = np.load(str(path))
    return data["vertices"], data["faces"]

